apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: '2017-09-18T06:34:05Z'
    labels:
      build: rmq
    name: rmq
    namespace: fbac
    resourceVersion: '19163'
    selfLink: /oapi/v1/namespaces/fbac/buildconfigs/rmq
    uid: 5e4197fa-9c3b-11e7-ad3b-ee82e32ea9ca
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: 'rmq:latest'
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      dockerStrategy: {}
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
      - github:
          secret: s5kyWXFpmVaQ6tnjINXk
        type: GitHub
      - generic:
          secret: QQtkNEZfeU3YGaNGp_g6
        type: Generic
  status:
    lastVersion: 1
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "rmq", "namespace": "", "kind": "DeploymentConfig"}]'
    name: rmq-service-pipeline
  spec:
    source:
      git:
        ref: master
        uri: https://github.com/bobbydeveaux/micro-rmq.git
      type: Git
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: ./Jenkinsfile
    triggers:
    - generic:
        secret: RandomPassword123
      type: Generic    
