apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    generation: 1
    labels:
      build: rmq
    name: rmq
    namespace: fbac
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    labels:
      build: rmq
    name: rmq
    namespace: fbac
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: 'rmq:latest'
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      dockerStrategy: {}
      type: Docker
    triggers:
      - github:
          secret: xoDZoMWEv06_sntOOr6J
        type: GitHub
      - generic:
          secret: R-f_K9TKmSepQUOCGqN2
        type: Generic
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "rmq", "namespace": "fbac", "kind": "DeploymentConfig"}]'
    name: rmq-service-pipeline
  spec:
    source:
      git:
        ref: master
        uri: https://github.com/bobbydeveaux/micro-rmq.git
      type: Git
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: ./Jenkinsfile
    triggers:
    - generic:
        secret: RandomPassword123
      type: Generic 
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: 'true'
    labels:
      app: rmq
    name: rmq
    namespace: fbac
  spec:
    host: rmq-fbac.127.0.0.1.nip.io
    port:
      targetPort: 15672-tcp
    to:
      kind: Service
      name: rmq
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
      - conditions:
          - lastTransitionTime: '2017-09-18T08:00:25Z'
            status: 'True'
            type: Admitted
        host: rmq-fbac.127.0.0.1.nip.io
        routerName: router
        wildcardPolicy: None

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    generation: 3
    labels:
      app: rmq
    name: rmq
    namespace: fbac
  spec:
    replicas: 1
    selector:
      app: rmq
      deploymentconfig: rmq
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: rmq
          deploymentconfig: rmq
      spec:
        containers:
          - imagePullPolicy: Always
            name: rmq
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: /var/lib/rabbitmq
                name: rmq-volume-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
          - emptyDir: {}
            name: rmq-volume-1
    test: false
    triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
            - rmq
          from:
            kind: ImageStreamTag
            name: 'rmq:latest'
            namespace: fbac
        type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: rmq
    name: rmq
    namespace: fbac
  spec:
    ports:
      - name: 4369-tcp
        port: 4369
        protocol: TCP
        targetPort: 4369
      - name: 5671-tcp
        port: 5671
        protocol: TCP
        targetPort: 5671
      - name: 5672-tcp
        port: 5672
        protocol: TCP
        targetPort: 5672
      - name: 15671-tcp
        port: 15671
        protocol: TCP
        targetPort: 15671
      - name: 15672-tcp
        port: 15672
        protocol: TCP
        targetPort: 15672
      - name: 25672-tcp
        port: 25672
        protocol: TCP
        targetPort: 25672
    selector:
      app: rmq
      deploymentconfig: rmq
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}

